variables:
  vmImageName: 'ubuntu-latest'

trigger: none

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(System.DefaultWorkingDirectory)/skillLinkProject
        npm install
        npm install jest
        npm run lint --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'

    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results/jest/*.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/skillLinkProject'

    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '**/coverage/cobertura-coverage.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/skillLinkProject'

    - task: CmdLine@2
      condition: always()
      inputs:
        script: |
          echo "Clean folder"
          cd $(System.DefaultWorkingDirectory)/skillLinkProject
          rm -rfv package-lock.json
          rm -rfv .git
          rm -rfv test-results
          rm -rfv coverage
          rm -rfv node_modules
          ls -l 

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      condition: always()
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload zip'
      condition: always()
      artifact: drop
